apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/ng: registry
  labels:
    app: ng2-pod
  name: ng2-pod
spec:
  containers:
  - args:
    - nginx
    - -g
    - daemon off;
    image: docker.io/library/nginx:latest
    name: ng_ct3
    ports:
    - containerPort: 80
      hostPort: 80
  restartPolicy: Always
